-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 13:48:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RoomMgmt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RoomMgmt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RoomMgmt` DEFAULT CHARACTER SET utf8 ;
USE `RoomMgmt` ;

-- -----------------------------------------------------
-- Table `RoomMgmt`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomMgmt`.`Room` (
  `roomId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`roomId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoomMgmt`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomMgmt`.`Event` (
  `eventId` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `organiser` TEXT NULL,
  PRIMARY KEY (`eventId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoomMgmt`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomMgmt`.`Reservation` (
  `reservationId` INT NOT NULL,
  `roomId` INT NOT NULL,
  `eventId` INT NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  PRIMARY KEY (`reservationId`),
  INDEX `fk_Reservation_Room_idx` (`roomId` ASC) ,
  INDEX `fk_Reservation_Event1_idx` (`eventId` ASC) ,
  CONSTRAINT `fk_Reservation_Room`
    FOREIGN KEY (`roomId`)
    REFERENCES `RoomMgmt`.`Room` (`roomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Event1`
    FOREIGN KEY (`eventId`)
    REFERENCES `RoomMgmt`.`Event` (`eventId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
